name: Staging

on:
  pull_request:
    branches:
      - "staging"

permissions:
  contents: read

jobs:
  test-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ secrets.STAGING_REPO }}
          event-type: test_staging
  run-fuzz:
    runs-on: ubuntu-latest # could be self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v3
        with:
          path: ./fuzz/corpus
          key: "${{ runner.os }}-fuzz-corpus-${{ hashFiles('**/Cargo.lock') }}"
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        id: check
        with:
          command: check
          args: --manifest-path ./fuzz/Cargo.toml
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-fuzz@0.11.1
      - run: |
          cargo build
          ./target/debug/vsmtp -c ./fuzz/server/vsmtp.vsl --no-daemon --stdout &
          cargo +nightly fuzz run client \
            -- -dict="./fuzz/dict/command.dict" -max_total_time=1200
          pkill vsmtp
      - uses: actions/upload-artifact@v3
        if: failure() && steps.check.outcome == 'success'
        with:
          name: artifacts
          path: ./fuzz/artifacts
